server:
  port: 8012

spring:
  datasource:
    url: jdbc:mysql://localhost:33065/admincontrol
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create
      # ddl-auto: none
      # ddl-auto: create-drop # DEV

redis:
  host: localhost
  port: 63795
  password: password

logging:
  level:
    root: INFO

jwt:
  secret: helloworld

