server:
  port: "${PORT:8012}"

spring:
  datasource:
    url: "${DB_URL:jdbc:mysql://localhost:33065/admincontrol}"
    username: "${DB_USER:root}"
    password: "${DB_PASS:password}"

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create
      # ddl-auto: none
      # ddl-auto: create-drop

redis:
  host: "${REDIS_HOST:localhost}"
  port: "${REDIS_PORT:63795}"
  password: "${REDIS_PASS:password}"

logging:
  level:
    root: INFO

jwt:
  secret: "${JWT_SECRET:helloworld}"
  aliveTimeFrame_second: 1800


